# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccef5c801b3028d8cb610780d86a18c241143d3ebf3feafa572cb8c767c3785649e78640893c66de9212d9d65964f9b67990c0757d2e1bd49880254ab1b5eb6a

test:
  secret_key_base: 855c3e0e96054ade5cd6f9b3e6b877aa76a6ee3b7a00b4d827f760b892b6f551d27d71ad99837d2be6b638f2b1f4cfabda22c6cf0ce8ffce0dcd484e0ce3e5c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
